### ISSUE TITLE
incomplete data ?

### ISSUE THREAD

**Issue by iTomxy** [XuyangGuo/CtrlHair#2]
Hi,
I got following error when running the [script_get_rgb_hsv_label.py](https://github.com/XuyangGuo/CtrlHair/blob/main/dataset_scripts/script_get_rgb_hsv_label.py) in preprocessing:
```
[ WARN:0@1.161] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/tianyou/codes/tmp.CtrlHair/dataset_info_ctrlhair/ffhq/label/69863.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "dataset_scripts/script_get_rgb_hsv_label.py", line 28, in <module>
    ds = DataFilter()
  File "/home/tianyou/codes/tmp.CtrlHair/./common_dataset.py", line 84, in __init__
    if self.valid_hair(path_join_abs(test_file, '../..'), test_file[-9:-4]):
  File "/home/tianyou/codes/tmp.CtrlHair/./common_dataset.py", line 103, in valid_hair
    if hat_region.mean() > 0.03:
AttributeError: 'bool' object has no attribute 'mean'
```
As I checked, there is no such `69863.png` raw image in the FFHQ dataset (i.e. in *ffhq/images_256/*). Also, there seems to be only `69080` images in total, which is inconsistent with the the number in *angle.csv*. Likewise, the CelebaMask_HQ dataset contains only `29677` instead of 30k images.

Are the provided datasets incomplete ?

**Comment by XuyangGuo** [comment]
Please make sure your download is complete, we checked the number of images again. It shows that the number of images in FFHQ and Celebamask_HQ are 70k and 30k respectively. And `69863.png` in _ffhq/images_256_ also exists. 

If you really have some special difficulty in downloading. You can also manually resize from the official cropped images of the FFHQ and CelebAMask_HQ datasets. Our images in `images_256` are nothing else special other than resolutions in 256.
