### ISSUE TITLE
The pretrained model returns 404 page.

### ISSUE THREAD

**Issue by zhangxiaodi** [XuyangGuo/CtrlHair#3]
Dear author, 
        When I want to download the [the pre-trained model of CtrlHair](https://drive.google.com/drive/folders/1opQhmc7ckS3J8qdLii_EMqmxYCcBLznO?usp=sharing), I meet the error 404 page.
you know, most of the computer vision researchers are Chinese guys.  Unfortunately, in china, the GFW a.k.a Great Fire Wall is powerful.
The research institution's VPN I am in is unstable when China is in some special period. So could you give me some download link from  the Baidu Netdisk or other places where Chinese research can download conveniently.

**Comment by XuyangGuo** [comment]
可以的，下面是3个对应百度网盘的链接，提取码都是1234：
[external_model_params](https://pan.baidu.com/s/1vnldtoT9G-5gfvUjjUSVOA?pwd=1234)
[model_trained](https://pan.baidu.com/s/1O_Hu5dnk4GwmUrIBDWpwFA?pwd=1234)
[dataset_info_ctrlhair](https://pan.baidu.com/s/1D3D2JqxIR6miCeMNssucKw?pwd=1234) 该路径需把其中的内容解压
