### ISSUE TITLE
Whole picture?

### ISSUE THREAD

**Issue by JACKYLUO1991** [XuyangGuo/CtrlHair#4]
What should I do if I do a hair change on the whole picture? Retrain or not?

**Comment by XuyangGuo** [comment]
Sorry, I don't quite understand your problem. Do you want to ask how to edit the whole portrait (rather than the cropped face image)?

**Comment by JACKYLUO1991** [comment]
@XuyangGuo yes...

**Comment by XuyangGuo** [comment]
@JACKYLUO1991  Our code does not directly support the editing of the whole portrait. The recommended method is to first crap the original picture, edit it, and then uncrop it back. 
`dataset_scripts/script_crop.py `and `external_code/crop.py` are the codes related to crop.
