### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Zlin0530** [XuyangGuo/CtrlHair#7]
This is a great job！ I recently tried to reproduce the code, I downloaded the dataset you provided using Baidu.com and there are three zip packages in it, I tried to extract all three zip packages but the data inside is the same. I mean what is the use of the "dataset_info_ctrlhair.z01" and "dataset_info_ctrlhair.z02" files? Can I just use the data from the "dataset_info_ctrlhair" zip file?
![%X6V 7 8WAHJ_CS81PLSST9](https://user-images.githubusercontent.com/107110150/226913607-45b01ca9-e08f-4aeb-a52a-c7bdbd4fed27.png)

**Comment by XuyangGuo** [comment]
You need to download all these three subpart zip, but only need to extract `dataset_info_ctrlhair.zip`. Because the data set is too large, I made a split for it. 
You can check the decompressed size to make sure it was decompressed correctly.
Thanks for your appreciation for our work.
